### ISSUE TITLE
----

### ISSUE THREAD

**Issue by worthless443** [higatowa/bento#11]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered (if any)**

**Additional context**

**Comment by himazawa** [comment]
@PatxiofromAlphensign would you mind to explain these issues? Thanks

**Comment by worthless443** [comment]
> @PatxiofromAlphensign would you mind to explain these issues? Thanks

My apologies, I accidentally posted a dummy issue.
